// jobs-data.ts
// Tipos e helpers — pode ser importado por Client e Server Components.
// Nao importa nada de 'next/headers' ou '@supabase/ssr'.

import type { JobStatus, JobType } from '@/lib/db/schema/enums'

export type { JobStatus, JobType }

// ─── TIPOS ────────────────────────────────────────────────────────────────────
export interface JobPayment {
  id: string
  type: string
  amount: number
  status: string
  dueDate: string
  method?: string
  paidAt?: string | null
}

export interface JobTask {
  id: string
  title: string
  completed: boolean
  priority: string
  autoGenerated?: boolean
  dueDate?: string | null
}

export interface JobHistoryEntry {
  id: string
  action: string
  fromStatus?: string | null
  toStatus?: string | null
  description?: string | null
  actorName?: string | null
  createdAt: string
}

export interface JobContract {
  id: string
  status: string
  formData?: Record<string, unknown> | null
  sentAt?: string | null
  signedAt?: string | null
}

export interface JobSdUsage {
  id: string
  sdLabel: string
  sdCamera?: string | null
  status: string
  backupPrimaryName?: string | null
  backupSecondaryName?: string | null
  backupPrimaryAt?: string | null
  safeToFormat: boolean
  formattedAt?: string | null
  photosCount?: number | null
  rawSizeGb?: number | null
}

export interface JobFull {
  id: string
  title: string
  type: JobType
  status: JobStatus
  clientId?: string | null
  clientName?: string | null
  clientPhone?: string | null
  clientEmail?: string | null
  contractedStudio?: string | null
  scheduledAt?: string | null
  endsAt?: string | null
  location?: { name: string; address?: string; city?: string } | null
  totalValue: number
  paidValue: number
  pendingValue: number
  sdCount: number
  editorId?: string | null
  editorName?: string | null
  driveLink?: string | null
  previewLink?: string | null
  whatsappLink?: string | null
  contractPdfUrl?: string | null
  // Locais do evento (preenchidos no fechamento do contrato)
  eventLocations?: {
    makingOf?:  { name: string; address?: string; time?: string } | null
    ceremony?:  { name: string; address?: string; time?: string } | null
    reception?: { name: string; address?: string; time?: string } | null
    arrivalTime?: string | null
  } | null
  tags: string[]
  notes?: string | null
  previewSentAt?: string | null
  deliveredAt?: string | null
  finalizedAt?: string | null
  canceledAt?: string | null
  cancelReason?: string | null
  createdAt: string
  contract?: JobContract | null
  payments: JobPayment[]
  tasks: JobTask[]
  history: JobHistoryEntry[]
  sdUsages: JobSdUsage[]
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────
export function getJobUrgency(job: JobFull): 'critical' | 'warning' | 'ok' {
  const overduePmt = job.payments.some(p =>
    p.status !== 'pago' && p.status !== 'estornado' && new Date(p.dueDate) < new Date()
  )
  const overdueSd = job.sdCount > 0 &&
    ['evento_realizado', 'sd_pendente'].includes(job.status) &&
    job.scheduledAt != null &&
    (Date.now() - new Date(job.scheduledAt).getTime()) > 3 * 86400_000
  if (overduePmt || overdueSd) return 'critical'
  const pendingTasks = job.tasks.filter(t => !t.completed && t.priority === 'urgente').length
  if (pendingTasks > 0) return 'warning'
  return 'ok'
}

export function getDaysUntilEvent(job: JobFull): number | null {
  if (!job.scheduledAt) return null
  return Math.ceil((new Date(job.scheduledAt).getTime() - Date.now()) / 86400_000)
}
