// jobs.ts — Server-only service layer
// Importa tipos e mocks de jobs-data.ts (safe para cliente)
// As funcoes getJobs/getJobById resolvem orgId automaticamente via Supabase.
// NAO importe este arquivo em Client Components — use jobs-data.ts.

export * from './jobs-data'

// ─── SERVER QUERIES ───────────────────────────────────────────────────────────
import type { JobFull } from './jobs-data'

// ─── INTERNAL: RESOLVE ORG ID ────────────────────────────────────────────────
async function getOrgId(): Promise<string | null> {
  try {
    const { createClient } = await import('@/lib/supabase/server')
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return null
    const { data } = await supabase
      .from('profiles')
      .select('org_id')
      .eq('id', user.id)
      .single()
    return (data as { org_id: string } | null)?.org_id ?? null
  } catch {
    return null
  }
}

export async function getJobs(): Promise<JobFull[]> {
  const orgId = await getOrgId()
  if (!orgId) return []
  try {
    const { createClient } = await import('@/lib/supabase/server')
    const supabase = await createClient()
    const { data, error } = await supabase
      .from('jobs')
      .select('*, clients(full_name, phone, email), payments(*), job_tasks(*), job_contracts(*)')
      .eq('org_id', orgId)
      .order('created_at', { ascending: false })
    if (error) throw error
    if (!data?.length) return []
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (data as any[]).map(mapDbJobToFull)
  } catch {
    return []
  }
}

export async function getJobById(id: string): Promise<JobFull | null> {
  const orgId = await getOrgId()
  if (!orgId) return null
  try {
    const { createClient } = await import('@/lib/supabase/server')
    const supabase = await createClient()
    const { data, error } = await supabase
      .from('jobs')
      .select(`*, clients(full_name, phone, email), payments(*), job_tasks(*), job_contracts(*), job_history(*),
        sd_card_usages(*, sd_cards(label, camera), backup_primary:storage_locations!backup_primary_id(name), backup_secondary:storage_locations!backup_secondary_id(name))`)
      .eq('id', id)
      .eq('org_id', orgId)
      .single()
    if (error) throw error
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return mapDbJobToFull(data as any)
  } catch {
    return null
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function mapDbJobToFull(data: any): JobFull {
  return {
    id: data.id, title: data.title, type: data.type, status: data.status,
    clientId: data.client_id,
    clientName: data.clients?.full_name ?? data.contracted_studio ?? null,
    clientPhone: data.clients?.phone ?? null,
    clientEmail: data.clients?.email ?? null,
    contractedStudio: data.contracted_studio,
    scheduledAt: data.scheduled_at, endsAt: data.ends_at, location: data.location,
    totalValue: parseFloat(data.total_value ?? '0'),
    paidValue: parseFloat(data.paid_value ?? '0'),
    pendingValue: parseFloat(data.pending_value ?? '0'),
    sdCount: data.sd_count ?? 0,
    editorId: data.editor_id, editorName: null,
    driveLink: data.drive_link, previewLink: data.preview_link,
    whatsappLink: data.whatsapp_link, contractPdfUrl: data.contract_pdf_url,
    tags: data.tags ?? [], notes: data.notes,
    previewSentAt: data.preview_sent_at, deliveredAt: data.delivered_at,
    finalizedAt: data.finalized_at, canceledAt: data.canceled_at,
    cancelReason: data.cancel_reason, createdAt: data.created_at,
    contract: data.job_contracts ? {
      id: data.job_contracts.id, status: data.job_contracts.status,
      formData: data.job_contracts.form_data,
      sentAt: data.job_contracts.sent_at, signedAt: data.job_contracts.signed_at,
    } : null,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    payments: (data.payments ?? []).map((p: any) => ({
      id: p.id, type: p.type, amount: parseFloat(p.amount),
      status: p.status, dueDate: p.due_date, method: p.method, paidAt: p.paid_at,
    })),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    tasks: (data.job_tasks ?? []).map((t: any) => ({
      id: t.id, title: t.title, completed: t.completed,
      priority: t.priority, autoGenerated: t.auto_generated, dueDate: t.due_date,
    })),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    history: (data.job_history ?? []).map((h: any) => ({
      id: h.id, action: h.action, fromStatus: h.from_status, toStatus: h.to_status,
      description: h.description, actorName: h.actor_name, createdAt: h.created_at,
    })),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    sdUsages: (data.sd_card_usages ?? []).map((s: any) => ({
      id: s.id, sdLabel: s.sd_cards?.label ?? s.sd_card_id, sdCamera: s.sd_cards?.camera,
      status: s.status, backupPrimaryName: s.backup_primary?.name,
      backupSecondaryName: s.backup_secondary?.name, backupPrimaryAt: s.backup_primary_at,
      safeToFormat: s.safe_to_format, formattedAt: s.formatted_at,
      photosCount: s.photos_count, rawSizeGb: s.raw_size_gb ? parseFloat(s.raw_size_gb) : null,
    })),
  }
}
